apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-rails-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: duongpham910/rails-capstone-project:tag
        ports:
        - containerPort: 3000
